# Docker image to start from
image: continuumio/miniconda3:latest

# Install additional dependencies
# procps-ng is required for nextflow to generate process statistics.
before_script:
  - conda env update --file env.yml
  - source activate deseq2icbi

# Execute some commands (e.g. `pytest` to execute python unit-tests,
# or run a nextflow pipeline)
test:
  stage: test
  script:
    - mkdir out
    - |
        ./runDESeq2_ICBI.R testdata/example1/sampleTableN.csv testdata/example1/merged_gene_counts.txt  --result_dir=out \
        --sample_col=sample --condition_col=overexpression \
        --c1=PFKFB3_S461E --c2=MOCK \
        --gtf_file=testdata/example1/gencode_subset.gtf
    - |
        ./runDESeq2_ICBI.R testdata/example1/sampleTableN.csv testdata/example1/merged_gene_counts.txt  --result_dir=out \
        --sample_col=sample --condition_col=overexpression \
        --c1=PFKFB3_S461E --c2=MOCK \
        --paired_grp=treatment \
        --covariate_formula="+numeric_covariate" \
        --gtf_file=testdata/example1/gencode_subset.gtf
    - |
        ./runDESeq2_ICBI.R testdata/example_nfcore/rnaseq_samplesheet.csv testdata/example_nfcore/salmon.merged.gene_counts.subset.tsv --result_dir=out \
        --sample_col=sample --nfcore \
        --c1=grpA --c2=grpB \
        --n_cpus=2

